apiVersion: v1
kind: ConfigMap
metadata:
  name: projectpulse-config
data:
  APP_ENV: "production"
  APP_PORT: "8000"
  DB_CONNECTION: "pgsql"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_DATABASE: "bilcode_test"
  LLM_PROVIDER: "google"
  LLM_MODEL: "gemini-2.5-flash"
  LLM_TIMEOUT_MS: "10000"

