apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectpulse-db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: projectpulse-config
                  key: DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: projectpulse-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: projectpulse-secret
                  key: DB_PASSWORD
